// Code generated by "stringer -type tokenType scanner.go"; DO NOT EDIT.

package json

import "fmt"

const (
	_tokenType_name_0 = "tokenInvalid"
	_tokenType_name_1 = "tokenComma"
	_tokenType_name_2 = "tokenColon"
	_tokenType_name_3 = "tokenKeyword"
	_tokenType_name_4 = "tokenNumber"
	_tokenType_name_5 = "tokenString"
	_tokenType_name_6 = "tokenBrackO"
	_tokenType_name_7 = "tokenBrackC"
	_tokenType_name_8 = "tokenBraceO"
	_tokenType_name_9 = "tokenBraceC"
)

var (
	_tokenType_index_0 = [...]uint8{0, 12}
	_tokenType_index_1 = [...]uint8{0, 10}
	_tokenType_index_2 = [...]uint8{0, 10}
	_tokenType_index_3 = [...]uint8{0, 12}
	_tokenType_index_4 = [...]uint8{0, 11}
	_tokenType_index_5 = [...]uint8{0, 11}
	_tokenType_index_6 = [...]uint8{0, 11}
	_tokenType_index_7 = [...]uint8{0, 11}
	_tokenType_index_8 = [...]uint8{0, 11}
	_tokenType_index_9 = [...]uint8{0, 11}
)

func (i tokenType) String() string {
	switch {
	case i == 0:
		return _tokenType_name_0
	case i == 44:
		return _tokenType_name_1
	case i == 58:
		return _tokenType_name_2
	case i == 75:
		return _tokenType_name_3
	case i == 78:
		return _tokenType_name_4
	case i == 83:
		return _tokenType_name_5
	case i == 91:
		return _tokenType_name_6
	case i == 93:
		return _tokenType_name_7
	case i == 123:
		return _tokenType_name_8
	case i == 125:
		return _tokenType_name_9
	default:
		return fmt.Sprintf("tokenType(%d)", i)
	}
}
