// Code generated by "stringer -type tokenType scanner.go"; DO NOT EDIT.

package json

import "fmt"

const _tokenType_name = "tokenInvalidtokenCommatokenColontokenKeywordtokenNumbertokenStringtokenBrackOtokenBrackCtokenBraceOtokenBraceCtokenEOF"

var _tokenType_map = map[tokenType]string{
	0:    _tokenType_name[0:12],
	44:   _tokenType_name[12:22],
	58:   _tokenType_name[22:32],
	75:   _tokenType_name[32:44],
	78:   _tokenType_name[44:55],
	83:   _tokenType_name[55:66],
	91:   _tokenType_name[66:77],
	93:   _tokenType_name[77:88],
	123:  _tokenType_name[88:99],
	125:  _tokenType_name[99:110],
	9220: _tokenType_name[110:118],
}

func (i tokenType) String() string {
	if str, ok := _tokenType_map[i]; ok {
		return str
	}
	return fmt.Sprintf("tokenType(%d)", i)
}
