package zclsyntax

// Generated by expression_vars_get.go. DO NOT EDIT.
// Run 'go generate' on this package to update the set of functions here.

import (
	"github.com/apparentlymart/go-zcl/zcl"
)

func (e *LiteralValueExpr) Variables() []zcl.Traversal {
	return Variables(e)
}

func (e *ScopeTraversalExpr) Variables() []zcl.Traversal {
	return Variables(e)
}
