// Code generated by "stringer -type TokenType -output token_type_string.go"; DO NOT EDIT.

package zclsyntax

import "fmt"

const _TokenType_name = "TokenNewlineTokenBangTokenBitwiseAndTokenOParenTokenCParenTokenStarTokenPlusTokenMinusTokenDotTokenSlashTokenColonTokenSemicolonTokenLessThanTokenEqualTokenGreaterThanTokenQuestionTokenCommentTokenOHeredocTokenIdentTokenNumberLitTokenStringLitTokenOBrackTokenCBrackTokenBitwiseXorTokenBacktickTokenCHeredocTokenOBraceTokenBitwiseOrTokenCBraceTokenBitwiseNotTokenOQuoteTokenCQuoteTokenTemplateControlTokenTemplateSeqEndTokenAndTokenOrTokenTemplateInterpTokenNotEqualTokenLessThanEqTokenGreaterThanEqTokenEOFTokenTabsTokenStarStarTokenInvalidTokenBadUTF8"

var _TokenType_map = map[TokenType]string{
	10:     _TokenType_name[0:12],
	33:     _TokenType_name[12:21],
	38:     _TokenType_name[21:36],
	40:     _TokenType_name[36:47],
	41:     _TokenType_name[47:58],
	42:     _TokenType_name[58:67],
	43:     _TokenType_name[67:76],
	45:     _TokenType_name[76:86],
	46:     _TokenType_name[86:94],
	47:     _TokenType_name[94:104],
	58:     _TokenType_name[104:114],
	59:     _TokenType_name[114:128],
	60:     _TokenType_name[128:141],
	61:     _TokenType_name[141:151],
	62:     _TokenType_name[151:167],
	63:     _TokenType_name[167:180],
	67:     _TokenType_name[180:192],
	72:     _TokenType_name[192:205],
	73:     _TokenType_name[205:215],
	78:     _TokenType_name[215:229],
	83:     _TokenType_name[229:243],
	91:     _TokenType_name[243:254],
	93:     _TokenType_name[254:265],
	94:     _TokenType_name[265:280],
	96:     _TokenType_name[280:293],
	104:    _TokenType_name[293:306],
	123:    _TokenType_name[306:317],
	124:    _TokenType_name[317:331],
	125:    _TokenType_name[331:342],
	126:    _TokenType_name[342:357],
	171:    _TokenType_name[357:368],
	187:    _TokenType_name[368:379],
	955:    _TokenType_name[379:399],
	8718:   _TokenType_name[399:418],
	8743:   _TokenType_name[418:426],
	8744:   _TokenType_name[426:433],
	8747:   _TokenType_name[433:452],
	8800:   _TokenType_name[452:465],
	8804:   _TokenType_name[465:480],
	8805:   _TokenType_name[480:498],
	9220:   _TokenType_name[498:506],
	9225:   _TokenType_name[506:515],
	10138:  _TokenType_name[515:528],
	65533:  _TokenType_name[528:540],
	128169: _TokenType_name[540:552],
}

func (i TokenType) String() string {
	if str, ok := _TokenType_map[i]; ok {
		return str
	}
	return fmt.Sprintf("TokenType(%d)", i)
}
