// Code generated by "stringer -type TokenType -output token_type_string.go"; DO NOT EDIT.

package zclsyntax

import "fmt"

const _TokenType_name = "TokenNilTokenNewlineTokenBangTokenPercentTokenBitwiseAndTokenOParenTokenCParenTokenStarTokenPlusTokenMinusTokenDotTokenSlashTokenColonTokenSemicolonTokenLessThanTokenEqualTokenGreaterThanTokenQuestionTokenCommentTokenOHeredocTokenIdentTokenNumberLitTokenQuotedLitTokenStringLitTokenOBrackTokenCBrackTokenBitwiseXorTokenBacktickTokenCHeredocTokenOBraceTokenBitwiseOrTokenCBraceTokenBitwiseNotTokenOQuoteTokenCQuoteTokenTemplateControlTokenTemplateSeqEndTokenAndTokenOrTokenTemplateInterpTokenNotEqualTokenLessThanEqTokenGreaterThanEqTokenEOFTokenTabsTokenStarStarTokenInvalidTokenBadUTF8"

var _TokenType_map = map[TokenType]string{
	0:      _TokenType_name[0:8],
	10:     _TokenType_name[8:20],
	33:     _TokenType_name[20:29],
	37:     _TokenType_name[29:41],
	38:     _TokenType_name[41:56],
	40:     _TokenType_name[56:67],
	41:     _TokenType_name[67:78],
	42:     _TokenType_name[78:87],
	43:     _TokenType_name[87:96],
	45:     _TokenType_name[96:106],
	46:     _TokenType_name[106:114],
	47:     _TokenType_name[114:124],
	58:     _TokenType_name[124:134],
	59:     _TokenType_name[134:148],
	60:     _TokenType_name[148:161],
	61:     _TokenType_name[161:171],
	62:     _TokenType_name[171:187],
	63:     _TokenType_name[187:200],
	67:     _TokenType_name[200:212],
	72:     _TokenType_name[212:225],
	73:     _TokenType_name[225:235],
	78:     _TokenType_name[235:249],
	81:     _TokenType_name[249:263],
	83:     _TokenType_name[263:277],
	91:     _TokenType_name[277:288],
	93:     _TokenType_name[288:299],
	94:     _TokenType_name[299:314],
	96:     _TokenType_name[314:327],
	104:    _TokenType_name[327:340],
	123:    _TokenType_name[340:351],
	124:    _TokenType_name[351:365],
	125:    _TokenType_name[365:376],
	126:    _TokenType_name[376:391],
	171:    _TokenType_name[391:402],
	187:    _TokenType_name[402:413],
	955:    _TokenType_name[413:433],
	8718:   _TokenType_name[433:452],
	8743:   _TokenType_name[452:460],
	8744:   _TokenType_name[460:467],
	8747:   _TokenType_name[467:486],
	8800:   _TokenType_name[486:499],
	8804:   _TokenType_name[499:514],
	8805:   _TokenType_name[514:532],
	9220:   _TokenType_name[532:540],
	9225:   _TokenType_name[540:549],
	10138:  _TokenType_name[549:562],
	65533:  _TokenType_name[562:574],
	128169: _TokenType_name[574:586],
}

func (i TokenType) String() string {
	if str, ok := _TokenType_map[i]; ok {
		return str
	}
	return fmt.Sprintf("TokenType(%d)", i)
}
