// Code generated by "stringer -type TokenType -output token_type_string.go"; DO NOT EDIT.

package zclsyntax

import "fmt"

const _TokenType_name = "TokenNewlineTokenBangTokenBitwiseAndTokenOParenTokenCParenTokenStarTokenPlusTokenMinusTokenDotTokenSlashTokenColonTokenSemicolonTokenLessThanTokenEqualTokenGreaterThanTokenQuestionTokenOHeredocTokenIdentTokenNumberLitTokenStringLitTokenOBrackTokenCBrackTokenBitwiseXorTokenBacktickTokenCHeredocTokenOBraceTokenBitwiseOrTokenCBraceTokenBitwiseNotTokenOQuoteTokenCQuoteTokenTemplateControlTokenTemplateSeqEndTokenAndTokenOrTokenTemplateInterpTokenNotEqualTokenLessThanEqTokenGreaterThanEqTokenEOFTokenTabsTokenStarStarTokenInvalidTokenBadUTF8"

var _TokenType_map = map[TokenType]string{
	10:     _TokenType_name[0:12],
	33:     _TokenType_name[12:21],
	38:     _TokenType_name[21:36],
	40:     _TokenType_name[36:47],
	41:     _TokenType_name[47:58],
	42:     _TokenType_name[58:67],
	43:     _TokenType_name[67:76],
	45:     _TokenType_name[76:86],
	46:     _TokenType_name[86:94],
	47:     _TokenType_name[94:104],
	58:     _TokenType_name[104:114],
	59:     _TokenType_name[114:128],
	60:     _TokenType_name[128:141],
	61:     _TokenType_name[141:151],
	62:     _TokenType_name[151:167],
	63:     _TokenType_name[167:180],
	72:     _TokenType_name[180:193],
	73:     _TokenType_name[193:203],
	78:     _TokenType_name[203:217],
	83:     _TokenType_name[217:231],
	91:     _TokenType_name[231:242],
	93:     _TokenType_name[242:253],
	94:     _TokenType_name[253:268],
	96:     _TokenType_name[268:281],
	104:    _TokenType_name[281:294],
	123:    _TokenType_name[294:305],
	124:    _TokenType_name[305:319],
	125:    _TokenType_name[319:330],
	126:    _TokenType_name[330:345],
	171:    _TokenType_name[345:356],
	187:    _TokenType_name[356:367],
	955:    _TokenType_name[367:387],
	8718:   _TokenType_name[387:406],
	8743:   _TokenType_name[406:414],
	8744:   _TokenType_name[414:421],
	8747:   _TokenType_name[421:440],
	8800:   _TokenType_name[440:453],
	8804:   _TokenType_name[453:468],
	8805:   _TokenType_name[468:486],
	9220:   _TokenType_name[486:494],
	9225:   _TokenType_name[494:503],
	10138:  _TokenType_name[503:516],
	65533:  _TokenType_name[516:528],
	128169: _TokenType_name[528:540],
}

func (i TokenType) String() string {
	if str, ok := _TokenType_map[i]; ok {
		return str
	}
	return fmt.Sprintf("TokenType(%d)", i)
}
