// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package hclsyntax

// Generated by expression_vars_gen.go. DO NOT EDIT.
// Run 'go generate' on this package to update the set of functions here.

import (
	"github.com/hashicorp/hcl/v2"
)

func (e *AnonSymbolExpr) Functions() []hcl.Traversal {
	return Functions(e)
}

func (e *BinaryOpExpr) Functions() []hcl.Traversal {
	return Functions(e)
}

func (e *ConditionalExpr) Functions() []hcl.Traversal {
	return Functions(e)
}

func (e *ExprSyntaxError) Functions() []hcl.Traversal {
	return Functions(e)
}

func (e *ForExpr) Functions() []hcl.Traversal {
	return Functions(e)
}

func (e *FunctionCallExpr) Functions() []hcl.Traversal {
	return Functions(e)
}

func (e *IndexExpr) Functions() []hcl.Traversal {
	return Functions(e)
}

func (e *LiteralValueExpr) Functions() []hcl.Traversal {
	return Functions(e)
}

func (e *ObjectConsExpr) Functions() []hcl.Traversal {
	return Functions(e)
}

func (e *ObjectConsKeyExpr) Functions() []hcl.Traversal {
	return Functions(e)
}

func (e *RelativeTraversalExpr) Functions() []hcl.Traversal {
	return Functions(e)
}

func (e *ScopeTraversalExpr) Functions() []hcl.Traversal {
	return Functions(e)
}

func (e *SplatExpr) Functions() []hcl.Traversal {
	return Functions(e)
}

func (e *TemplateExpr) Functions() []hcl.Traversal {
	return Functions(e)
}

func (e *TemplateJoinExpr) Functions() []hcl.Traversal {
	return Functions(e)
}

func (e *TemplateWrapExpr) Functions() []hcl.Traversal {
	return Functions(e)
}

func (e *TupleConsExpr) Functions() []hcl.Traversal {
	return Functions(e)
}

func (e *UnaryOpExpr) Functions() []hcl.Traversal {
	return Functions(e)
}
