<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>hcl</string>
      <string>hcldec</string>
    </array>
    <key>name</key>
    <string>HCL</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>begin</key>
        <string>#|//</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.hcl</string>
          </dict>
        </dict>
        <key>comment</key>
        <string>Comments</string>
        <key>end</key>
        <string>$\n?</string>
        <key>name</key>
        <string>comment.line.hcl</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>/\*</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.hcl</string>
          </dict>
        </dict>
        <key>comment</key>
        <string>Block comments</string>
        <key>end</key>
        <string>\*/</string>
        <key>name</key>
        <string>comment.block.hcl</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.hcl</string>
          </dict>
        </dict>
        <key>comment</key>
        <string>Nested Blocks</string>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.hcl</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.block.hcl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>string.hcl punctuation.definition.string.begin.hcl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.value.hcl</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>string.hcl punctuation.definition.string.end.hcl</string>
          </dict>
        </dict>
        <key>comment</key>
        <string>Quoted Block Labels</string>
        <key>match</key>
        <string>(&#34;)([^&#34;]+)(&#34;)</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>(\w+)\s*(=)\s*</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.other.assignment.hcl</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.hcl</string>
          </dict>
        </dict>
        <key>comment</key>
        <string>Attribute Definitions</string>
        <key>end</key>
        <string>$</string>
        <key>name</key>
        <string>meta.attr.hcl</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>source.hclexpr</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.other.hcl</string>
          </dict>
        </dict>
        <key>comment</key>
        <string>Keywords</string>
        <key>match</key>
        <string>[-\w]+</string>
      </dict>
    </array>
    <key>scopeName</key>
    <string>source.hcl</string>
    <key>uuid</key>
    <string>55e8075d-e2e3-4e44-8446-744a9860e476</string>
  </dict>
</plist>